stages:
  - build
  - release

build-home-x86_64:
  stage: build
  tags:
    - privileged
  script:
    - dnf install -y lorax wget rpm-ostree git hfsplus-tools
    - ostree init --repo repo --mode archive
    - ostree remote add --no-gpg-verify --repo repo tauOS https://repo.tauos.co/ostree tau/home/1/x86_64
    - ostree pull --repo repo --mirror tauOS tau/home/1/x86_64
    - |
      lorax --product=tauOS \
      --version=1 \
      --release=1 \
      --variant=home \
      --source=https://kojipkgs.fedoraproject.org/compose/35/latest-Fedora-35/compose/Everything/x86_64/os/ \
      --source=https://repo.tauos.co/releases/1/ \
      --installpkgs=tau-logos \
      --installpkgs=tau-release \
      --installpkgs=tau-release-identity \
      --installpkgs=tau-release-ostree-desktop \
      --installpkgs=tau-repos \
      --installpkgs=tau-gpg-keys \
      --installpkgs=fedora-repos \
      --installpkgs=tau-anaconda-profiles \
      --volid=tauOS-Home-Installer \
      --macboot \
      --skip-branding \
      --add-template=$(pwd)/lorax-configure-repo.tmpl \
      --add-template=$(pwd)/lorax-embed-repo.tmpl \
      --add-template-var=ostree_install_repo=file://$(pwd)/repo \
      --add-template-var=ostree_update_repo=https://repo.tauos.co/ostree \
      --add-template-var=ostree_osname=tauOS \
      --add-template-var=ostree_oskey=tauOS-home \
      --add-template-var=ostree_contenturl=https://repo.tauos.co/ostree \
      --add-template-var=ostree_install_ref=tau/home/1/x86_64 \
      --add-template-var=ostree_update_ref=tau/home/1/x86_64 \
      --logfile=$(pwd)/lorax.log \
      --tmp=$(pwd)/tmp \
      --rootfs-size=8 \
      $(pwd)/home-x86_64
    - echo HOME_x86_64_JOB_ID=$CI_JOB_ID >> generate_executables.env
  artifacts:
    paths:
      - home-x86_64
    reports:
      dotenv: generate_executables.env

build-home-aarch64:
  stage: build
  tags:
    - privileged-arm
  script:
    - dnf install -y lorax wget rpm-ostree git hfsplus-tools
    - ostree init --repo repo --mode archive
    - ostree remote add --no-gpg-verify --repo repo tauOS https://repo.tauos.co/ostree tau/home/1/aarch64
    - ostree pull --repo repo --mirror tauOS tau/home/1/aarch64
    - |
      lorax --product=tauOS \
      --version=1 \
      --release=1 \
      --variant=home \
      --source=https://kojipkgs.fedoraproject.org/compose/35/latest-Fedora-35/compose/Everything/aarch64/os/ \
      --source=https://repo.tauos.co/releases/1/ \
      --installpkgs=tau-logos \
      --installpkgs=tau-release \
      --installpkgs=tau-release-identity \
      --installpkgs=tau-release-ostree-desktop \
      --installpkgs=tau-repos \
      --installpkgs=tau-gpg-keys \
      --installpkgs=fedora-repos \
      --installpkgs=tau-anaconda-profiles \
      --volid=tauOS-Home-Installer \
      --macboot \
      --skip-branding \
      --add-template=$(pwd)/lorax-configure-repo.tmpl \
      --add-template=$(pwd)/lorax-embed-repo.tmpl \
      --add-template-var=ostree_install_repo=file://$(pwd)/repo \
      --add-template-var=ostree_update_repo=https://repo.tauos.co/ostree \
      --add-template-var=ostree_osname=tauOS \
      --add-template-var=ostree_oskey=tauOS-home \
      --add-template-var=ostree_contenturl=https://repo.tauos.co/ostree \
      --add-template-var=ostree_install_ref=tau/home/1/aarch64 \
      --add-template-var=ostree_update_ref=tau/home/1/aarch64 \
      --logfile=$(pwd)/lorax.log \
      --tmp=$(pwd)/tmp \
      --rootfs-size=8 \
      $(pwd)/home-aarch64
    - echo HOME_AARCH64_JOB_ID=$CI_JOB_ID >> generate_executables.env
  artifacts:
    paths:
      - home-aarch64
    reports:
      dotenv: generate_executables.env

release-all:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  script:
    - echo 'running release_job'
  needs:
    - job: build-home-x86_64
      artifacts: true
    - job: build-home-aarch64
      artifacts: true
  release:
    name: 'Release Images $CI_COMMIT_SHORT_SHA'
    description: '$CI_COMMIT_MESSAGE'
    tag_name: '$CI_COMMIT_SHORT_SHA-$CI_JOB_ID'
    assets:
      links:
        - name: 'Home Installer (x86_64)'
          url: 'https://sourceview.innatical.com/tauos/isos/-/jobs/${HOME_x86_64_JOB_ID}/artifacts/raw/home-x86_64/images/boot.iso?inline=false'
        - name: 'Home Installer (x86_64)'
          url: 'https://sourceview.innatical.com/tauos/isos/-/jobs/${HOME_AARCH64_JOB_ID}/artifacts/raw/home-aarch64/images/boot.iso?inline=false'
  only:
    - main
