stages:
  - build
  - release

build_desktop:
  stage: build
  tags:
    - privileged
  script:
    - dnf install -y lorax wget rpm-ostree git
    - ostree init --repo repo --mode archive
    - ostree remote add --repo repo tau https://ostree.tau.innatical.com tau/core/1/x86_64
    - wget -qO- https://tauos.co/gpg.asc | ostree remote gpg-import --repo repo --stdin tau 
    - until ostree pull --repo repo tau tau/core/1/x86_64; do echo "Try again"; done
    - git clone https://pagure.io/fedora-lorax-templates.git
    - lorax --product=tauOS \
      --version=1 \
      --release=prerelease \
      --source=https://kojipkgs.fedoraproject.org/compose/35/latest-Fedora-35/compose/Everything/x86_64/os/ \
      --source=https://repo.tauos.co/releases/1/ \
      --installpkgs=tau-logos \
      --installpkgs=tau-release \
      --variant=Desktop \
      --volid=tauOS-Desktop-Installer \
      --macboot \
      --skip-branding \
      --add-template=$(pwd)/fedora-lorax-templates/ostree-based-installer/lorax-configure-repo.tmpl \
      --add-template=$(pwd)/fedora-lorax-templates/ostree-based-installer/lorax-embed-repo.tmpl \
      --add-template-var=ostree_install_repo=file://$(pwd)/repo \
      --add-template-var=ostree_update_repo=file://$(pwd)/repo \
      --add-template-var=ostree_osname=tauOS \
      --add-template-var=ostree_oskey=tauOS-desktop \
      --add-template-var=ostree_contenturl=https://ostree.tau.innatical.com \
      --add-template-var=ostree_install_ref=tau/core/1/x86_64 \
      --add-template-var=ostree_update_ref=tau/core/1/x86_64 \
      --logfile=$(pwd)/lorax.log \
      --tmp=$(pwd)/tmp \
      --rootfs-size=8 \
      $(pwd)/desktop_x86_64
  artifacts:
    paths:
      - desktop_x86_64

release_all:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  script:
    - echo 'running release_job'
    - echo 'Previous Job ID is printed below'
    - echo $GE_JOB_ID
  needs:
    - job: build_desktop
      artifacts: true
  release:
    name: 'Release Images $CI_COMMIT_SHORT_SHA'
    description: '$CI_COMMIT_MESSAGE'
    tag_name: '$CI_COMMIT_SHORT_SHA'
    assets:
      links:
        - name: 'Desktop Installer (x86_64)'
          url: 'https://sourceview.innatical.com/tauos/isos/-/jobs/${GE_JOB_ID}/artifacts/file/desktop_x86_64'
  only:
    - main
